import { GeneratedMedia } from '../types';

export const INITIAL_GALLERY: GeneratedMedia[] = [
  {
    id: 'sample-video-1',
    type: 'video',
    prompt: 'Veo 3 cinematic hyper-motion: Cyberpunk pilot walking toward a glowing supersonic jet in heavy neon rain',
    enhancedPrompt: 'Veo 3 cinematic hyper-motion: Cyberpunk pilot wearing reflective carbon helmet walking toward glowing supersonic stealth jet in heavy neon rain, cinematic 24fps motion blur, reflections in puddles',
    model: 'veo-3',
    modelName: 'Veo 3 (DeepMind)',
    style: 'cinematic',
    styleLabel: 'Cinematic',
    aspectRatio: '16:9',
    duration: '5s',
    cameraMotion: 'pan-right',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 1000 * 60 * 30, // 30 mins ago
    isFavorite: true,
    likesCount: 142,
    seed: 49281,
    authorName: 'DeepMind Cinephile',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'sample-image-1',
    type: 'image',
    prompt: 'Flux.1 Dev: Celestial cosmic empress crowned with golden stars and floating nebula crystals, 8k portrait',
    enhancedPrompt: 'Flux.1 Dev: Celestial cosmic empress crowned with intricate golden starlight filigree and floating glowing nebula crystals, photorealistic skin pores, Hasselblad 8k',
    model: 'flux-dev',
    modelName: 'Flux.1 Dev',
    style: 'photoreal',
    styleLabel: 'Photoreal 8K',
    aspectRatio: '9:16',
    mediaUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 1000 * 60 * 90,
    isFavorite: true,
    likesCount: 289,
    seed: 81723,
    authorName: 'Starlight Art',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'sample-image-2',
    type: 'image',
    prompt: 'Nana Banana v2.5: Anime girl with turquoise braided hair summoning glowing origami butterflies under cherry blossoms',
    enhancedPrompt: 'Nana Banana v2.5: Anime girl with glowing turquoise braids summoning bioluminescent origami butterflies under moonlit sakura blossoms, Makoto Shinkai lighting',
    model: 'nana-banana',
    modelName: 'Nana Banana v2.5',
    style: 'anime',
    styleLabel: 'Anime / Manga',
    aspectRatio: '1:1',
    mediaUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 1000 * 60 * 180,
    isFavorite: false,
    likesCount: 95,
    seed: 12903,
    authorName: 'AnimeVanguard',
    authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'sample-video-2',
    type: 'video',
    prompt: 'Kling 1.5 HD: FPV drone flying rapidly through a futuristic cyber canyon with massive hologram waterfalls',
    enhancedPrompt: 'Kling 1.5 HD: Fast FPV drone swooping through towering neon canyon with cascading digital waterfalls, 60fps high motion physics, realistic volumetric spray',
    model: 'kling-1.5',
    modelName: 'Kling 1.5 HD',
    style: 'cyberpunk',
    styleLabel: 'Cyberpunk Neon',
    aspectRatio: '9:16',
    duration: '10s',
    cameraMotion: 'fpv-drone',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 1000 * 60 * 360,
    isFavorite: true,
    likesCount: 412,
    seed: 63019,
    authorName: 'DronePilot_AI',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'sample-image-3',
    type: 'image',
    prompt: 'Flux.1 Schnell: Hypercar concept sculpted with matte black carbon fiber and glowing cyan plasma wheels on salt flats',
    enhancedPrompt: 'Flux.1 Schnell: Aerodynamic hypercar concept sculpted with matte carbon weave, active aero fins, glowing cyan plasma rim reflections on wet Bonneville salt flats',
    model: 'flux-schnell',
    modelName: 'Flux.1 Schnell',
    style: 'photoreal',
    styleLabel: 'Photoreal 8K',
    aspectRatio: '16:9',
    mediaUrl: 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?w=800&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 1000 * 60 * 600,
    isFavorite: false,
    likesCount: 78,
    seed: 34912,
    authorName: 'SpeedDesign',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'sample-video-3',
    type: 'video',
    prompt: 'Veo 3: Mythical golden dragon taking off from a mountain peak into an ocean of pink sunset clouds',
    enhancedPrompt: 'Veo 3: Mythical golden winged dragon launching gracefully off jagged snow peak into ocean of pink volumetric sunset clouds, realistic wing air currents',
    model: 'veo-3',
    modelName: 'Veo 3 (DeepMind)',
    style: 'fantasy',
    styleLabel: 'Fantasy Oil',
    aspectRatio: '16:9',
    duration: '5s',
    cameraMotion: 'orbit-360',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 1000 * 60 * 1200,
    isFavorite: true,
    likesCount: 520,
    seed: 99120,
    authorName: 'MythicRealm',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80'
  }
];

export const EXPLORE_FEED: GeneratedMedia[] = [
  ...INITIAL_GALLERY,
  {
    id: 'explore-1',
    type: 'image',
    prompt: 'Nana Banana: Cyber samurai kitsune with glowing purple katanas in rainy Shibuya crosswalk, 4k concept art',
    enhancedPrompt: 'Nana Banana: Cyber samurai kitsune wearing futuristic ronin robes, twin purple plasma katanas, reflections in wet neon Shibuya pavement',
    model: 'nana-banana',
    modelName: 'Nana Banana v2.5',
    style: 'anime',
    styleLabel: 'Anime / Manga',
    aspectRatio: '9:16',
    mediaUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 1000 * 60 * 1800,
    isFavorite: false,
    likesCount: 681,
    seed: 44211,
    authorName: 'NeoTokyoArtist',
    authorAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'explore-2',
    type: 'video',
    prompt: 'Kling 1.5 HD: Adorable 3D robot puppy running through a field of glowing bioluminescent flowers at twilight',
    enhancedPrompt: 'Kling 1.5 HD: Playful Pixar style robot pup bounding through iridescent wildflower field, big expressive glowing optics, soft ambient lighting',
    model: 'kling-1.5',
    modelName: 'Kling 1.5 HD',
    style: '3d-render',
    styleLabel: '3D Pixar',
    aspectRatio: '1:1',
    duration: '5s',
    cameraMotion: 'zoom-in',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 1000 * 60 * 2400,
    isFavorite: true,
    likesCount: 890,
    seed: 77218,
    authorName: 'CuteBotStudios',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 'explore-3',
    type: 'image',
    prompt: 'Flux.1 Dev: Ancient overgrown greenhouse in a misty gothic forest with floating luminous spores and sun rays',
    enhancedPrompt: 'Flux.1 Dev: Enormous Victorian glass conservatory swallowed by giant emerald ferns and bioluminescent moss, soft golden dust motes in morning godrays',
    model: 'flux-dev',
    modelName: 'Flux.1 Dev',
    style: 'photoreal',
    styleLabel: 'Photoreal 8K',
    aspectRatio: '16:9',
    mediaUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80',
    createdAt: Date.now() - 1000 * 60 * 3000,
    isFavorite: false,
    likesCount: 345,
    seed: 11904,
    authorName: 'NatureMystic',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80'
  }
];
